service: dev-lake

provider:
  name: aws
  profile: renanbym
  runtime: nodejs10.x
 
  region: us-east-1
  memorySize: 128
  timeout: 30
  versionFunctions: false

  iamRoleStatements:
    - Effect: 'Allow'
      Action: 
        - 'lambda:InvokeFunction'
      Resource: 
        - '*'

    - Effect: 'Allow'
      Action: 
        - 'sqs:*'
      Resource: 
        - '*'

    - Effect: 'Allow'
      Action: 
        - 'es:*'
      Resource: 
        - '*'

plugins:
  - serverless-prune-plugin
  - serverless-offline

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 3

package:
  enviroment: dev

functions:

  ping:
    handler: services/ping.handler
    events:
      - http:
          path: /ping
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true
             
  build:
    handler: build.handler

  searchGoogle:
    handler: search-google.handler

  updateProfile:
    handler: update-profile.handler

  getOneProfile:
    handler: get-profile.handler
    events:
      - http: 
          path: /{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

  getAllProfile:
    handler: get-profile.handler
    events:
      - http: 
          path: /
          method: get
          cors: true