service: dev-lake

provider:
  name: aws
  profile: renanbym
  runtime: nodejs10.x
 
  region: us-east-1
  memorySize: 128
  timeout: 30
  versionFunctions: false

  iamRoleStatements:
    - Effect: 'Allow'
      Action: 
        - 'lambda:InvokeFunction'
      Resource: 
        - '*'

    - Effect: 'Allow'
      Action: 
        - 'sqs:*'
      Resource: 
        - '*'

    - Effect: 'Allow'
      Action: 
        - 'es:*'
      Resource: 
        - '*'

plugins:
  - serverless-offline

custom:

package:
  individually: true
  include:
    - ../../node_modules/**
    - ../_core/**
    - ../models/**

functions:

  ping:
    handler: services/ping.handler
    events:
      - http:
          path: /ping
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true
             
  build:
    handler: build.handler

  searchGoogle:
    handler: search-google.handler

  updateProfile:
    handler: update-profile.handler
    timeout: 300 
    reservedConcurrency: 20
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:${file(../../config/config.yml):ACCOUNT}:updateProfileQueue
          batchSize: 1  

  getOneProfile:
    handler: get-profile.handler
    events:
      - http: 
          path: /{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

  getAllProfile:
    handler: get-profile.handler
    events:
      - http: 
          path: /
          method: get
          cors: true

  rankingPermanencia:
    handler: ranking-permanencia.handler

resources:
  Resources:

    ProcessCreateLists:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "updateProfileQueue"
        VisibilityTimeout: 300

        